---
title: "Haloferax volcanii RosR growth curves"
author: "Amy Schmid"
date: "2024-10-21"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#fresh start
rm(list = ls())

library(tidyverse)

```


#read in the data
```{r}
Filtered_data_AKS <- read.csv('Hv_filter_AKS.csv')

```

#plot for SF1
```{r}
Filtered_data_short <- filter (Filtered_data_AKS, Time <= 30)
#pdf("FigS1_Hv_growth_rawplot_final.pdf", width = 4, height = 8)
ggplot(Filtered_data_short, aes(x=Time, y=OD)) +
  geom_point(aes(color = Strain), size = 0.5, alpha = 0.2) +
  geom_smooth(method = 'gam', formula = y ~ s(x, bs = "cs"),
              aes(color = Strain)) +
  scale_y_log10(limits=c(0.01, 1.5)) +
  scale_color_manual(values = c("black", "salmon")) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600") +
  theme(legend.position ='bottom') +
  facet_wrap(~factor(Condition, levels=c('standard', '0.5 mM H2O2', '1 mM H2O2', '0.667 mM paraquat')), ncol = 1)
#dev.off()

```


#Now plot only the gam geom smooth curves for main text figures
```{r}
Filtered_data_short <- filter (Filtered_data_AKS, Time <= 30)
pdf("Fig3_Hv_growth_gamplot.pdf", width = 4, height = 8)
ggplot(Filtered_data_short, aes(x=Time, y=OD)) +
 # geom_point(aes(color = Strain), size = 0.5, alpha = 0.2) +
  geom_smooth(method = 'gam', formula = y ~ s(x, bs = "cs"),
              aes(color = Strain)) +
  scale_y_log10(limits=c(0.01, 1.5)) +
  scale_color_manual(values = c("black", "salmon")) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600") +
  theme(legend.position ='bottom') +
  facet_wrap(~factor(Condition, levels=c('standard', '0.5 mM H2O2', '1 mM H2O2', '0.667 mM paraquat')), ncol = 1)
 
  NULL
dev.off()
#Looks like rosR may have a phenotype under 0.5mM H2O2. Is this significant? Use rmd file "rosR_bsd_AKS_git.rmd" to calculate AUC and mu, detect significant differences.
```



#Plot titrations for pyrE (FigA)
```{r}
#subset relevant conditions

  
    H2O2 <-subset(Filtered_data, Condition == 'standard' | Condition == '0.5 mM H2O2' | Condition == '1 mM H2O2' | Condition == '2 mM H2O2') %>%
  filter(Strain == "pyrE2") %>%
  filter (Time <=30) 
  
paraquat <- subset(Filtered_data, Condition == 'standard' | Condition == '0.333 mM paraquat' | Condition == '0.667 mM paraquat')  %>%
  filter(Strain == "pyrE2") %>%
  filter (Time <=30) 
#write.csv (titr, file = "Hv_growth_titration.csv")
#fill in "standard" into "oxidant" column for standard growth condition in excel
```


```{r}
#plot H2O2 titration subpanel

#set colors
cond.cols.h2o2 <- c(`standard` = "black", `0.5 mM H2O2` = "orange4",  `1 mM H2O2` ="orange", `2 mM H2O2` = "grey")

#print supp figure with all datapoints
pdf("FigS1_Hv_H2O2_growth_gamplot.pdf", width = 4, height =4)
ggplot(H2O2, aes(x=Time, y=OD)) +
  geom_point(aes(color = Condition), size = 0.5, alpha = 0.2) +
  geom_smooth(aes(color = Condition), method = 'gam', formula = y ~ s(x, bs = "cs")) +
  scale_y_log10(limits=c(0.01, 1.5)) +
  scale_color_manual(values = cond.cols.h2o2) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600") +
  theme(legend.position ='bottom') 
 # facet_wrap(~oxidant) +
 
  
dev.off()
#print summary geom smooth plot for simplified main text figure
pdf("Fig2_Hv_H2O2_growth_gamplot.pdf", width = 4, height = 4)
ggplot(H2O2, aes(x=Time, y=OD)) +
 # geom_point(aes(color = Condition), size = 0.5, alpha = 0.2) +
  geom_smooth(aes(color = Condition), method = 'gam', formula = y ~ s(x, bs = "cs")) +
  scale_y_log10(limits=c(0.01, 1.5)) +
  scale_color_manual(values = cond.cols.h2o2) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600") +
  theme(legend.position ='bottom') 
 # facet_wrap(~oxidant) +
 
  
dev.off()
```

```{r}

#plot PQ titration subpanel, main text
cond.cols.PQ <- c(`standard` = "black", `0.333 mM paraquat` = "orange4", `0.667 mM paraquat` = "orange")

pdf("Fig2_Hv_PQ_growth_gamplot.pdf", width = 4, height = 4)
ggplot(paraquat, aes(x=Time, y=OD)) +
 # geom_point(aes(color = Condition), size = 0.5, alpha = 0.2) +
  geom_smooth(aes(color = Condition), method = 'gam', formula = y ~ s(x, bs = "cs")) +
  scale_y_log10(limits=c(0.01, 1.5)) +
 # scale_color_manual(values = c("black", "red")) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600", title = "Paraquat") +
  theme(legend.position ='bottom') +
  scale_color_manual(values = cond.cols.PQ) +
  
 # facet_wrap(~oxidant) +
 
  NULL
dev.off()


#plot PQ titration subpanel, supplement
cond.cols.PQ <- c(`standard` = "black", `0.333 mM paraquat` = "orange4", `0.667 mM paraquat` = "orange")

pdf("FigS1_Hv_PQ_growth_gamplot.pdf", width = 4, height = 4)
ggplot(paraquat, aes(x=Time, y=OD)) +
  geom_point(aes(color = Condition), size = 0.5, alpha = 0.2) +
  geom_smooth(aes(color = Condition), method = 'gam', formula = y ~ s(x, bs = "cs")) +
  scale_y_log10(limits=c(0.01, 1.5)) +
 # scale_color_manual(values = c("black", "red")) +
  theme_minimal() +
  labs(x="Time (hours)", y="OD600", title = "Paraquat") +
  theme(legend.position ='bottom') +
  scale_color_manual(values = cond.cols.PQ) +
  
 # facet_wrap(~oxidant) +
 
  NULL
dev.off()

```







                     
                     



